### ISSUE TITLE
Puppet 4 version

### ISSUE THREAD

**Issue by pietertheunissen** [CygnusNetworks/cygnus-puppet-disk-facter#13]
Do you have any plans to release a puppet 4 version anytime soon?

**Comment by cygnusb** [comment]
I currently have no Puppet 4 Installation to test this on, since we currently are on Puppet 3.x and migration is scheduled for later this year. So expect no immediate update for this.

**Comment by baurmatt** [comment]
@cygnusb Any update on this? :)

**Comment by cygnusb** [comment]
We have switched to Puppet 4 and I do not have any issues

**Comment by cygnusb** [comment]
Since no other comment was made and this is working on Puppet 4 for us, I will close this issue
